name: reusable workflow

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Run Reusable Build Setup
      run: echo ' This is a reusable workflow'
